#pragma config(Sensor, S4,     sonarSensor,         sensorSONAR)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*--------------------------------------------------------------------------------------------------------*\
|*                                                                                                        *|
|*                                   - Obstacle Detection with Sonar -                                    *|
|*                                            ROBOTC on NXT                                               *|
|*                                                                                                        *|
|*  This program runs your robot forward until it detects and obstacle, at which point it stops.          *|
|*                                                                                                        *|
|*                                        ROBOT CONFIGURATION                                             *|
|*    NOTES:                                                                                              *|
|*    1)  The Sonar Sensor should be somewhere on the FRONT of the robot, facing FORWARD.                 *|
|*                                                                                                        *|
|*    MOTORS & SENSORS:                                                                                   *|
|*    [I/O Port]              [Name]              [Type]              [Description]                       *|
|*    Port B                  motorB              NXT                 Right motor                         *|
|*    Port C                  motorC              NXT                 Left motor                          *|
|*    Port 4                  sonarSensor         Sonar Sensor        Front mounted, front facing         *|
\*---------------------------------------------------------------------------------------------------4246-*/

#define SPEED 30
#define K 6

task main()
{
  int desired_dist = 30;   // Create variable 'distance_in_cm' and initialize it to 20(cm).

  while (true) {

    int C =  K*(SensorValue[sonarSensor] - desired_dist);

    nxtDisplayBigStringAt(0, 50,"s:%d",SensorValue[sonarSensor]);

       motor[motorB] = C;    // Motor B is stopped at a 0 power level
       motor[motorC] = C;    // Motor C is stopped at a 0 power level


 }
}
